// ID identifying the cluster to create. Use your username so that resources created can be tracked back to you.
cluster_id = "ocp"
// Domain of the cluster. This should be "${cluster_id}.${base_domain}".
cluster_domain = "ocp.yasen.local"
// Base domain from which the cluster domain is a subdomain.
base_domain = "yasen.local"


vsphere_server = "vc.yasen.local"
vsphere_user = "administrator@yasen.local"
vsphere_password = "VMware1!"
vsphere_cluster = "Rack1"
vsphere_datacenter = "Datacenter1"
vsphere_datastore = "NFS"
vm_template = "rhcos-4.3.8-x86_64-vmware.x86_64"
vm_network = "ocp4-segment"
machine_cidr = "10.114.16.0/24"
bootstrap_ip = "10.114.16.9"
control_plane_ips = ["10.114.16.10", "10.114.16.11", "10.114.16.12"]
compute_ips = ["10.114.16.20", "10.114.16.21", "10.114.16.22"]

control_plane_count = 3
compute_count = 3

// URL of the bootstrap ignition. This needs to be publicly accessible so that the bootstrap machine can pull the ignition.
bootstrap_ignition_url = "http://10.114.209.37/bootstrap.ign"

// Ignition config for the control plane machines. You should copy the contents of the master.ign generated by the installer.
control_plane_ignition = <<END_OF_MASTER_IGNITION
{"ignition":{"config":{"append":[{"source":"https://api-int.ocp.yasen.local:22623/config/master","verification":{}}]},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJTHA5Y3FkUkRRSll3RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEl3TURNeU9EQXdNRE14T1ZvWApEVE13TURNeU5qQXdNRE14T1Zvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2VFBGU2xPMkY5R1MKcDBKRkZ1cmJyTi9yYU9jQkcyZW1HWUxhSzF4TlNXV0Mvc1dnTTZyZkZsMkhWRGMrVWc0cExrdnZJMDBEeW85RgpaNitheEFveER6NjJ5NFRDb0c2VXM3TTUyK0VXanRVZ0w3R3NINHJORFNLdEZHc0tSb0RyMmJWWlA3TkVScWRqCndPVkRxMy90eEFEV3RtUmtEWFJpbTZWSmJBUnhuck9KVGVpTDZQdWFwYUUycCs0aEhyeVFKcGxhV3h0dkh6K2QKUmwvTjIxRGxuMXVNbnNXaURhMXN4YXE1NXZIUE9sSDhnZVF2eDBOT2VWeXVHRE9vekFpais0MFptU0tkcGNUWApMbW4rTTZvOGsyb1BCajdiZjVJOTZYdElIeEtsTXBxTEVoT01VQ0tmQVo0V0R4Y2hqZ0pVNHJWdnZFVmQzNHp6CnNQNnUxVGJCRlFJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVUlhZ3Baamd1RmpOcUYwVFF4MDZmN0ZZNlVJMHdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQURpOU8xOE9TWUZyekN6eCs1d1BFV2Jrc3oyMVdyeG1tVk44b0JXZ1plVmJaMU1vT0Qrb29OTytRS0x0CkhLWmFuUndVOUtwSU9qTVhJS0xuVkNFU1liYlU3SzJqc0hjYW9HOEpJZjhrSXJ2NEsrUS81Sms0NGpYZzF5dTIKeHhDNkNoZUxXMjFxVXFmUSsrQytIcXZUY2RPaXphRC9nSEdpTVpSc3k5Z3d1UXNqNmRhMFB2ZFpUMGN5dWNWdwpsNHJxMWhmb1o2VEtUOHQwMFp1M0JXQ05JeHBHemlvazNQNXZaVlg3ajhCMTBnb1krYk5YcmRuVWpObnNCZzlYCmhYNVBMazIzc3dpT05sNGkyWHBkM0t6bWhuSUErOWhSZmZLUlZCa2ZON3dwY1FTaTF2cFZPcUNHTU9FOW55d00KR1lzTUQzNzl1ZkYvdHRmeEI4VldNQmNwOGV3PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","verification":{}}]}},"timeouts":{},"version":"2.2.0"},"networkd":{},"passwd":{},"storage":{},"systemd":{}}
END_OF_MASTER_IGNITION

// Ignition config for the compute machines. You should copy the contents of the worker.ign generated by the installer.
compute_ignition = <<END_OF_WORKER_IGNITION
{"ignition":{"config":{"append":[{"source":"https://api-int.ocp.yasen.local:22623/config/worker","verification":{}}]},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJTHA5Y3FkUkRRSll3RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEl3TURNeU9EQXdNRE14T1ZvWApEVE13TURNeU5qQXdNRE14T1Zvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2VFBGU2xPMkY5R1MKcDBKRkZ1cmJyTi9yYU9jQkcyZW1HWUxhSzF4TlNXV0Mvc1dnTTZyZkZsMkhWRGMrVWc0cExrdnZJMDBEeW85RgpaNitheEFveER6NjJ5NFRDb0c2VXM3TTUyK0VXanRVZ0w3R3NINHJORFNLdEZHc0tSb0RyMmJWWlA3TkVScWRqCndPVkRxMy90eEFEV3RtUmtEWFJpbTZWSmJBUnhuck9KVGVpTDZQdWFwYUUycCs0aEhyeVFKcGxhV3h0dkh6K2QKUmwvTjIxRGxuMXVNbnNXaURhMXN4YXE1NXZIUE9sSDhnZVF2eDBOT2VWeXVHRE9vekFpais0MFptU0tkcGNUWApMbW4rTTZvOGsyb1BCajdiZjVJOTZYdElIeEtsTXBxTEVoT01VQ0tmQVo0V0R4Y2hqZ0pVNHJWdnZFVmQzNHp6CnNQNnUxVGJCRlFJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVUlhZ3Baamd1RmpOcUYwVFF4MDZmN0ZZNlVJMHdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQURpOU8xOE9TWUZyekN6eCs1d1BFV2Jrc3oyMVdyeG1tVk44b0JXZ1plVmJaMU1vT0Qrb29OTytRS0x0CkhLWmFuUndVOUtwSU9qTVhJS0xuVkNFU1liYlU3SzJqc0hjYW9HOEpJZjhrSXJ2NEsrUS81Sms0NGpYZzF5dTIKeHhDNkNoZUxXMjFxVXFmUSsrQytIcXZUY2RPaXphRC9nSEdpTVpSc3k5Z3d1UXNqNmRhMFB2ZFpUMGN5dWNWdwpsNHJxMWhmb1o2VEtUOHQwMFp1M0JXQ05JeHBHemlvazNQNXZaVlg3ajhCMTBnb1krYk5YcmRuVWpObnNCZzlYCmhYNVBMazIzc3dpT05sNGkyWHBkM0t6bWhuSUErOWhSZmZLUlZCa2ZON3dwY1FTaTF2cFZPcUNHTU9FOW55d00KR1lzTUQzNzl1ZkYvdHRmeEI4VldNQmNwOGV3PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","verification":{}}]}},"timeouts":{},"version":"2.2.0"},"networkd":{},"passwd":{},"storage":{},"systemd":{}}
END_OF_WORKER_IGNITION
